version = 0.1

[default.local_start_api.parameters]
env_vars = "env.json"
docker_network = "recipes-network"

[default.deploy.parameters]
stack_name = "aws-lambda-recipes-api-micronaut"
resolve_s3 = true
s3_prefix = "aws-lambda-recipes-api-micronaut"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
